### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by weiym07** [jirouvan/ads1299-and-f4-mcu#1]
求教

**Comment by weiym07** [comment]
您的实现代码我可以学习一下吗？

**Comment by weiym07** [comment]
您的ADS1299的EPRO文件 能在上传一下吗  球球了

**Comment by dxqqq** [comment]
兄弟你好 ，可以再上传一次吗，想参考一下 感谢！

**Comment by weiym07** [comment]
兄弟你也在做脑电吗？

**Comment by dxqqq** [comment]
是的

**Comment by TingYhan** [comment]
兄弟们有没有参考代码，十分感谢！！！

**Comment by zhihaoxi** [comment]
大佬，借个代码看看呗，球球了：）

**Comment by weiym07** [comment]
现在 嘉立创有开源ads1299项目 非常完整&nbsp; 你可以去看一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月3日(周二) 中午11:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jirouvan/ads1299-and-f4-mcu] 求教 (Issue #1)




 
大佬，借个代码看看呗，球球了：）

**Comment by jirouvan** [comment]
我的上位机写的全是bug，暂时只开源硬件部分，你可以先用YuTao的，他写的快

**Comment by jirouvan** [comment]
spi通信直接用的正点原子官方库，我写的比较乱，整理一下上传
